version: '3.0'

volumes:
  jenkins_home:

services:
  jenkins-dood:
    container_name: jenkins-dood
    environment:
      - TZ=PST
#    image: pitkley/jenkins-dood:lts
    image: jenkins-test:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/urandom:/dev/random
      - jenkins_home:/var/jenkins_home
    ports:
      - 8080:8080
